import asyncio
import csv
import os
import subprocess
import tempfile
from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP("WizTree")

WIZTREE_PATH = r"C:\Program Files\WizTree\WizTree64.exe"

@mcp.tool()
async def wiztree_analyze(path: str, top_n: int = 20) -> str:
    """
    Analyzes a directory using WizTree and returns the top N largest files/folders.
    
    Args:
        path: The absolute path to the directory or drive to analyze (e.g., "C:\Users\AHMED").
        top_n: The number of largest items to return.
    """
    if not os.path.exists(path):
        return f"Error: Path '{path}' does not exist."

    if not os.path.exists(WIZTREE_PATH):
        return f"Error: WizTree not found at '{WIZTREE_PATH}'."

    fd, temp_csv = tempfile.mkstemp(suffix=".csv")
    os.close(fd)
    
    try:
        # Run WizTree to export data to CSV
        cmd = [
            WIZTREE_PATH,
            path,
            f"/export={temp_csv}",
            "/admin=0",
        ]
        
        # We use subprocess.run, which will wait until the process exits
        subprocess.run(cmd, check=True)
        
        results = []
        with open(temp_csv, "r", encoding="utf-8", errors="replace") as f:
            reader = csv.reader(f)
            
            # WizTree CSV has a "Generated by" message in the first line
            header1 = next(reader, None)
            if header1 and header1 and header1[0].startswith("Generated"):
                headers = next(reader, None)
            else:
                headers = header1

            for row in reader:
                if len(row) < 4:
                    continue
                file_name = row[0]
                
                try:
                    size = int(row[1])
                except ValueError:
                    size = 0
                    
                allocated = row[2]
                modified = row[3]
                
                # Skip the root path itself to only show children
                if file_name.rstrip("\\") == path.rstrip("\\"):
                    continue
                    
                results.append({
                    "name": file_name,
                    "size_bytes": size,
                    "allocated_bytes": allocated,
                    "modified": modified
                })
        
        # Sort by size descending
        results.sort(key=lambda x: x["size_bytes"], reverse=True)
        
        top_results = results[:top_n]
        
        output = [f"Top {len(top_results)} largest items in '{path}':"]
        for i, item in enumerate(top_results, 1):
            # Convert bytes to GB or MB for readability
            size_bytes = item["size_bytes"]
            if size_bytes > 1024**3:
                size_str = f"{size_bytes / (1024**3):.2f} GB"
            else:
                size_str = f"{size_bytes / (1024**2):.2f} MB"
                
            output.append(f"{i}. {item['name']} - {size_str}")
            
        return "\n".join(output)

    except subprocess.CalledProcessError as e:
        return f"Error running WizTree: {e}"
    except Exception as e:
        return f"An error occurred: {str(e)}"
    finally:
        # Clean up the temporary CSV file
        if os.path.exists(temp_csv):
            try:
                os.remove(temp_csv)
            except:
                pass

if __name__ == "__main__":
    # When run directly, start the FastMCP stdio server
    mcp.run()
